apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: recipe-admin
  labels:
    app.kubernetes.io/name: recipe-admin
    app.kubernetes.io/component: ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  rules:
    - host: recipe-admin.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: recipe-admin
                port:
                  number: 80
