apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-admin
spec:
  template:
    spec:
      containers:
        - name: recipe-admin
          env:
            - name: ENVIRONMENT
              value: "production"
