apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: recipe-admin
spec:
  tls:
    - hosts:
      - recipe-admin.apps.jacobingalls.info
      secretName: wildcard-apps-jacobingalls-info-tls
  rules:
    - host: recipe-admin.apps.jacobingalls.info
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: recipe-admin
                port:
                  number: 80
