apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - admin/

labels:
  - pairs:
      app.kubernetes.io/part-of: recipe-admin
      app.kubernetes.io/managed-by: argocd
    includeSelectors: true
